# Generated by Django 5.2.1 on 2025-05-15 18:12

from django.db import migrations, models
import os
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_notification_options_remove_book_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books/', null=True, blank=True),
        ),
    ]
