# Generated by Django 5.2.1 on 2025-05-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_covers/default_book_cover.jpg', upload_to='book_covers/'),
        ),
    ]
