# Generated by Django 5.2.1 on 2025-05-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('global', 'Global'), ('system', 'System'), ('book_added', 'Book Added'), ('book_edited', 'Book Edited'), ('book_removed', 'Book Removed'), ('book_borrowed', 'Book Borrowed'), ('book_returned', 'Book Returned')], max_length=20),
        ),
    ]
