# Generated by Django 5.2.1 on 2025-05-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_genre_book_average_rating_book_total_borrows_and_more'),
    ]

    operations = [
    ]
