# Generated by Django 5.2.1 on 2025-05-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_migrate_existing_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='books.book'),
        ),
    ]
