# Generated by Django 5.2.1 on 2025-05-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='images/books/default-cover.jpg', null=True, upload_to='books/'),
        ),
    ]
