# Generated by Django 5.2.1 on 2025-05-21 01:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookReview',
            new_name='Review',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='text',
        ),
    ]
